pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        // Checkout the repository
        checkout scm
      }
    }

    stage('Copy files - Backend') {
        steps {
          dir("backend") {
            script {
                sshagent(['saba']) {
                    def bastionIP = '3.83.223.231'
                    def privateIP = '10.0.5.122'
                    def privateKeyPath = '/home/ubuntu/saba.pem'

                    // Step 1: Copy files from Jenkins to the bastion host
                    sh "scp -o StrictHostKeyChecking=no -r * ubuntu@${bastionIP}:/home/ubuntu/"

                    // Step 2: Copy files from the bastion host to the private server
                    sh "ssh -o StrictHostKeyChecking=no -i ${privateKeyPath} ubuntu@${bastionIP} 'mkdir -p /home/ubuntu/del && sudo scp -o StrictHostKeyChecking=no -r /home/ubuntu/* /del/'"

                    // Step 3: Execute commands on the private server
                    //sh "ssh -o StrictHostKeyChecking=no -i ${privateKeyPath} -J ubuntu@${bastionIP} ubuntu@${privateIP} 'sudo npm install && sudo pm2 start npm --name \"saba\" -- start'"
                }
            }
          }
        }
    }

  }
}
