pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        // Checkout the repository
        checkout scm
      }
    }

        stage('Copy files - Backend') {
        steps {
            dir('backend') {
                script {
                    sh "scp -o StrictHostKeyChecking=no -i /home/ubuntu/saba.pem -r * ubuntu@3.83.223.231:/home/ubuntu/"
                    sh "ssh -o StrictHostKeyChecking=no -i /home/ubuntu/saba.pem ubuntu@3.83.223.231 'ssh -o StrictHostKeyChecking=no -i /home/ubuntu/saba.pem ubuntu@10.0.5.122 \"sudo npm install && sudo pm2 start npm --name \\\"saba\\\" -- start\"'"
                }
            }
        }
    }

  }
}
